name: build-test-using-reusable-workflow
on: push
jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: eeashar20/actions-learning-pathway/.github/workflows/build-test-reusable-workflow.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
